import _default from 'next/dist/client/router'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home(props) {

  // export async function getStaticProps(){
  //   const {data} = ...

  //   return{
  //     props: data
  //   }
  // }

  return (
    <>
      <Head>
        <title>Kotam App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Patient with results, impatient with action. - Naval Ravikant</h1> 
      </div>
    </>
  )
}
